onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /wbs_part_delta_sigma_tb/wbs_ready
add wave -noupdate /wbs_part_delta_sigma_tb/snk_adr
add wave -noupdate /wbs_part_delta_sigma_tb/snk_tgd
add wave -noupdate /wbs_part_delta_sigma_tb/a
add wave -noupdate /wbs_part_delta_sigma_tb/b
add wave -noupdate /wbs_part_delta_sigma_tb/c
add wave -noupdate /wbs_part_delta_sigma_tb/d
add wave -noupdate /wbs_part_delta_sigma_tb/x
add wave -noupdate /wbs_part_delta_sigma_tb/y
add wave -noupdate /wbs_part_delta_sigma_tb/q
add wave -noupdate /wbs_part_delta_sigma_tb/sum
add wave -noupdate /wbs_part_delta_sigma_tb/src_adr
add wave -noupdate /wbs_part_delta_sigma_tb/src_tgd
add wave -noupdate /wbs_part_delta_sigma_tb/end_of_file
add wave -noupdate /wbs_part_delta_sigma_tb/clk
add wave -noupdate /wbs_part_delta_sigma_tb/rst
add wave -noupdate /wbs_part_delta_sigma_tb/ce
add wave -noupdate /wbs_part_delta_sigma_tb/snk_i
add wave -noupdate /wbs_part_delta_sigma_tb/snk_o
add wave -noupdate /wbs_part_delta_sigma_tb/src_i
add wave -noupdate /wbs_part_delta_sigma_tb/src_o
add wave -noupdate /wbs_part_delta_sigma_tb/valid_out_procedure
add wave -noupdate /wbs_part_delta_sigma_tb/valid_out
add wave -noupdate /wbs_part_delta_sigma_tb/valid_new
add wave -noupdate /wbs_part_delta_sigma_tb/ce_counter
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/clk_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/rst_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/ce_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/snk_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/snk_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/src_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/src_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/dat_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/dat_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/busy_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/valid_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/valid_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/ce_core_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/clk
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/rst
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/ce
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/out_to_sink_snk
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/sink_to_out_snk
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/out_to_source_src
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/source_to_out_src
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/sink_to_core_dat
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/sink_to_r_adr
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/sink_to_r_tgd
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/sink_to_core_valid
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/source_to_or_busy
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/core_to_source_dat
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/core_to_r_valid
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/core_to_or_busy
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/or_to_sink_busy
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/wrapper_to_core_ce_core
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/r_to_source_adr
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/r_to_source_tgd
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/r_to_source_valid
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/wrapper/r_to_pipeline_update
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/a_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/b_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/c_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/d_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/kx_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/ky_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/ksum_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/clk_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/ce_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/valid_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/valid_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/rst_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/x_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/y_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sum_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_ac_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_db_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sigma
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sigma_ac
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sigma_db
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_ac_pos
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_ac_rdo
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_db_pos
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_db_rdo
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_pos
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_rdo
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/valid_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/a_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/b_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/c_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/d_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/kx_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/ky_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/ksum_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/clk_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/ce_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/valid_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/valid_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/rst_i
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/x_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/y_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sum_o
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_ac_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_db_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_pre
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sigma
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sigma_ac
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/sigma_db
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_ac_pos
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_ac_rdo
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_db_pos
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/diff_db_rdo
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_pos
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/q_rdo
add wave -noupdate /wbs_part_delta_sigma_tb/DUT/core/valid_pre
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {890092 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2048 ns}
