# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a200tffg1156-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vitor.ferreira/Clones/dsp-cores/hdl/syn/artix/wbs_cordic_iter/wbs_cordic_iter_top.cache/wt [current_project]
set_property parent.project_path /home/vitor.ferreira/Clones/dsp-cores/hdl/syn/artix/wbs_cordic_iter/wbs_cordic_iter_top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/wbstream/wb_stream_pkg.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/rp_math_pack/rp_math_pack.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/ip_cores/general-cores/modules/genrams/genram_pkg.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/cordic_iter/cordic_iter.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/wbstream/wb_stream_source.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/wbstream/wb_stream_sink.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/ip_cores/general-cores/modules/wishbone/wishbone_pkg.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/cordic_iter/cordic.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/wbstream/wb_stream_wrapper.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/dsp_cores_pkg.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/wbs_cordic_iter/wbs_cordic_iter.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/modules/ce_gen/ce_gen.vhd
  /home/vitor.ferreira/Clones/dsp-cores/hdl/top/artix/wbs_cordic_iter/wbs_cordic_iter_top.vhd
}
read_xdc /home/vitor.ferreira/Clones/dsp-cores/hdl/syn/artix/wbs_cordic_iter/top.xdc
set_property used_in_implementation false [get_files /home/vitor.ferreira/Clones/dsp-cores/hdl/syn/artix/wbs_cordic_iter/top.xdc]

catch { write_hwdef -file wbs_cordic_iter_top.hwdef }
synth_design -top wbs_cordic_iter_top -part xc7a200tffg1156-1
write_checkpoint -noxdef wbs_cordic_iter_top.dcp
catch { report_utilization -file wbs_cordic_iter_top_utilization_synth.rpt -pb wbs_cordic_iter_top_utilization_synth.pb }
