onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /wbs_mixer_tb/s_wbs_ready
add wave -noupdate /wbs_mixer_tb/s_snk_adr
add wave -noupdate /wbs_mixer_tb/s_snk_tgd
add wave -noupdate /wbs_mixer_tb/s_snk_dat_0
add wave -noupdate /wbs_mixer_tb/s_src_adr
add wave -noupdate /wbs_mixer_tb/s_src_tgd
add wave -noupdate /wbs_mixer_tb/s_src_dat_0
add wave -noupdate /wbs_mixer_tb/s_end_of_file
add wave -noupdate /wbs_mixer_tb/s_clk
add wave -noupdate /wbs_mixer_tb/s_rst
add wave -noupdate /wbs_mixer_tb/s_ce
add wave -noupdate /wbs_mixer_tb/s_snk_i
add wave -noupdate /wbs_mixer_tb/s_snk_o
add wave -noupdate /wbs_mixer_tb/s_src_i
add wave -noupdate /wbs_mixer_tb/s_src_o
add wave -noupdate /wbs_mixer_tb/s_valid_out_procedure
add wave -noupdate /wbs_mixer_tb/s_valid_out
add wave -noupdate /wbs_mixer_tb/s_valid_new
add wave -noupdate /wbs_mixer_tb/s_ce_counter
add wave -noupdate /wbs_mixer_tb/DUT/clk_i
add wave -noupdate /wbs_mixer_tb/DUT/rst_i
add wave -noupdate /wbs_mixer_tb/DUT/ce_i
add wave -noupdate /wbs_mixer_tb/DUT/snk_i
add wave -noupdate /wbs_mixer_tb/DUT/snk_o
add wave -noupdate /wbs_mixer_tb/DUT/src_i
add wave -noupdate /wbs_mixer_tb/DUT/src_o
add wave -noupdate /wbs_mixer_tb/DUT/s_clk
add wave -noupdate /wbs_mixer_tb/DUT/s_rst
add wave -noupdate /wbs_mixer_tb/DUT/s_ce
add wave -noupdate /wbs_mixer_tb/DUT/s_snk_i
add wave -noupdate /wbs_mixer_tb/DUT/s_snk_o
add wave -noupdate /wbs_mixer_tb/DUT/s_src_i
add wave -noupdate -expand /wbs_mixer_tb/DUT/s_src_o
add wave -noupdate /wbs_mixer_tb/DUT/s_dat_o
add wave -noupdate /wbs_mixer_tb/DUT/s_dat_i
add wave -noupdate /wbs_mixer_tb/DUT/s_busy_i
add wave -noupdate /wbs_mixer_tb/DUT/s_valid_o
add wave -noupdate /wbs_mixer_tb/DUT/s_valid_i
add wave -noupdate /wbs_mixer_tb/DUT/s_ce_core_o
add wave -noupdate /wbs_mixer_tb/DUT/temp_i
add wave -noupdate /wbs_mixer_tb/DUT/temp_o
add wave -noupdate /wbs_mixer_tb/DUT/clk_i
add wave -noupdate /wbs_mixer_tb/DUT/rst_i
add wave -noupdate /wbs_mixer_tb/DUT/ce_i
add wave -noupdate /wbs_mixer_tb/DUT/snk_i
add wave -noupdate /wbs_mixer_tb/DUT/snk_o
add wave -noupdate /wbs_mixer_tb/DUT/src_i
add wave -noupdate /wbs_mixer_tb/DUT/src_o
add wave -noupdate /wbs_mixer_tb/DUT/s_clk
add wave -noupdate /wbs_mixer_tb/DUT/s_rst
add wave -noupdate /wbs_mixer_tb/DUT/s_ce
add wave -noupdate /wbs_mixer_tb/DUT/s_snk_i
add wave -noupdate /wbs_mixer_tb/DUT/s_snk_o
add wave -noupdate /wbs_mixer_tb/DUT/s_src_i
add wave -noupdate /wbs_mixer_tb/DUT/s_src_o
add wave -noupdate /wbs_mixer_tb/DUT/s_dat_o
add wave -noupdate /wbs_mixer_tb/DUT/s_dat_i
add wave -noupdate /wbs_mixer_tb/DUT/s_busy_i
add wave -noupdate /wbs_mixer_tb/DUT/s_valid_o
add wave -noupdate /wbs_mixer_tb/DUT/s_valid_i
add wave -noupdate /wbs_mixer_tb/DUT/s_ce_core_o
add wave -noupdate /wbs_mixer_tb/DUT/temp_i
add wave -noupdate /wbs_mixer_tb/DUT/temp_o
add wave -noupdate /wbs_mixer_tb/DUT/ce_temp
add wave -noupdate /wbs_mixer_tb/DUT/r_valid_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {761436 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {4096 ns}
