function Hd = polyphase_post_monit_1(Fs, decim_factor)
%POLYPHASE_POST_MONIT_1 Returns a multirate filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.13 and the DSP System Toolbox 8.1.
%
% Generated on: 23-Apr-2013 10:53:51
%

Hd = mfilt.firdecim(decim_factor);

% [EOF]
