files = ["icon_1_port/chipscope_icon_1_port.ngc",
	"icon_2_port/chipscope_icon_2_port.ngc",
	"icon_4_port/chipscope_icon_4_port.ngc",
	"icon_1_port/chipscope_icon_1_port.vhd",
	"icon_2_port/chipscope_icon_2_port.vhd",
	"icon_4_port/chipscope_icon_4_port.vhd",
	"ila/chipscope_ila.ngc", 
	"ila/chipscope_ila.vhd", 
	"ila_1t_128d/chipscope_ila_1t_128d.ngc", 
	"ila_1t_128d/chipscope_ila_1t_128d.vhd", 
	"vio/chipscope_vio_256.ngc",
	"vio/chipscope_vio_256.vhd"]
