files = ["multiplier_s32_s32_s64.ngc",
	"multiplier_s32_s32_s64.vhd",
        "adder_u32_s32_s34.vhd",
        "adder_u32_s32_s34.ngc",
        "dds_beam_position.vhd",
        "dds_beam_position.ngc",
	"dds_carrier.ngc",
	"dds_carrier.vhd",
	"dds_mixer.ngc",
	"dds_mixer.vhd",
	"dds_adc_input.ngc",
	"dds_adc_input.v",
	"cic_130M_100k.ngc",
	"cic_130M_100k.vhd"
	]
